[package]
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "type-hash"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["std"]
std = []

[dependencies]

[lints]
workspace = true
