[package]
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "type-hash"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["std"]
std = []
alloy = ["dep:alloy-primitives"]
uuid = ["dep:uuid"]

[dependencies]
alloy-primitives = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[lints]
workspace = true
