[package]
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "flux-utils"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bytes = { workspace = true, optional = true }
core_affinity.workspace = true
directories.workspace = true
flux-timing.workspace = true
libc.workspace = true
rand.workspace = true
serde.workspace = true
spin.workspace = true
thiserror.workspace = true
tracing.workspace = true
type-hash.workspace = true
wincode = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true
crossbeam-channel.workspace = true
flux-communication.workspace = true
tinyvec.workspace = true

[features]
bytes = ["dep:bytes"]
default = []
wincode = ["dep:wincode"]

[[bench]]
harness = false
name = "arrayvec"

[[bench]]
harness = false
name = "dcache"

[lints]
workspace = true
