[package]
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "flux-timekeeper"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
auto_impl.workspace = true
bitflags.workspace = true
crossterm.workspace = true
flux.workspace = true
indexmap.workspace = true
ratatui.workspace = true
serde.workspace = true
signal-hook.workspace = true
strum.workspace = true

[[bin]]
name = "timekeeper"
path = "bin/timekeeper.rs"

[lints]
workspace = true
