[package]
edition.workspace = true
license.workspace = true
name = "flux-ctl"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "flux_ctl"
path = "src/lib.rs"

[[bin]]
name = "flux-ctl"
path = "src/main.rs"

[dependencies]
clap.workspace = true
crossterm.workspace = true
flux.workspace = true
flux-communication.workspace = true
flux-timing.workspace = true
flux-utils.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
shared_memory.workspace = true

[dev-dependencies]
ctrlc.workspace = true
tempfile.workspace = true
tracing.workspace = true

[lints]
workspace = true
