[package]
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "flux-network"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
byte-stable.workspace = true
flux.workspace = true
flux-communication.workspace = true
flux-timing.workspace = true
flux-utils.workspace = true
httparse.workspace = true
libc.workspace = true
mio.workspace = true
rustls = { workspace = true, optional = true }
serde.workspace = true
tracing.workspace = true
webpki-roots = { workspace = true, optional = true }
wincode = { workspace = true, optional = true }

[dev-dependencies]
core_affinity.workspace = true
criterion.workspace = true
rcgen.workspace = true
spine-derive.workspace = true
tempfile.workspace = true
wincode = { workspace = true }
wincode-derive = { workspace = true }

[features]
tls = ["dep:rustls", "dep:webpki-roots"]

[[test]]
name = "http_tls"
required-features = ["tls"]

[[bench]]
harness = false
name = "connector"

[[bench]]
harness = false
name = "udp_pipeline"

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["serde"]
