[package]
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "flux-communication"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
directories.workspace = true
flux-timing.workspace = true
flux-utils.workspace = true
libc.workspace = true
mio = { workspace = true, optional = true }
rand.workspace = true
shared_memory.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true

[features]
park = ["dep:mio"]
