[package]
description = "Gather versioned leaves into blobs: ship them over TCP, persist them to disk"
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "flux-gather"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
flux.workspace = true
flux-disk.workspace = true
flux-network.workspace = true
flux-timing.workspace = true
flux-versioned-types.workspace = true
mio.workspace = true
tracing.workspace = true

[dev-dependencies]
flux-utils.workspace = true
serde.workspace = true
spine-derive.workspace = true
tempfile.workspace = true
type-hash-derive.workspace = true

[package.metadata.cargo-machete]
ignored = ["serde"]

[lints]
workspace = true
