[package]
description = "Generic data-gather sender, receiver, and disk persister over versioned blobs"
edition.workspace = true
keywords = ["communication", "low-latency", "performance"]
license.workspace = true
name = "flux-gather"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
flux.workspace = true
flux-disk.workspace = true
flux-network.workspace = true
flux-timing.workspace = true
flux-utils.workspace = true
flux-versioned-types.workspace = true
bincode.workspace = true
mio.workspace = true
serde.workspace = true
spine-derive.workspace = true
tracing.workspace = true
type-hash-derive.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["bincode"]
